# Generated by Django 3.2 on 2023-04-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title_id',
            new_name='title',
        ),
    ]
